version: "3.9"

services:
  backend:
    build:
      context: ./Backend
    volumes:
      - ./Backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./Frontend
    volumes:
      - ./Frontend:/app
    ports:
      - "3000:3000"
    env_file:
      - ./Frontend/.env
    depends_on:
      - backend

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: matchdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

volumes:
  postgres_data:
